monolog:
    channels:
        - deprecation
        - security
        - request

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stderr
                level: debug
                channels: ["!event"]
                formatter: monolog.formatter.line

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: php://stderr
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
                channels: ["!event"]

            nested:
                type: stream
                path: php://stderr
                level: info
                formatter: monolog.formatter.json

            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                level: notice
                formatter: monolog.formatter.json

            security:
                type: stream
                channels: [security]
                path: php://stderr
                level: warning
                formatter: monolog.formatter.json
