version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php public/index.php"
  relay: pipes
  env:
    APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
    PHP_IDE_CONFIG: 'serverName=crypto-rates'
    XDEBUG_CONFIG: 'idekey=PHPSTORM client_host=host.docker.internal client_port=9003'

http:
  address: 0.0.0.0:8080
  middleware: ["gzip", "static"]
  static:
    dir: "public"
    forbid: [".php", ".htaccess"]
  uploads:
    forbid: [".php", ".exe", ".bat", ".cmd", ".sh"]
  pool:
    num_workers: 1
    debug: true
    supervisor:
      watch_tick: 1s
      ttl: 0s
      idle_ttl: 10s
      exec_ttl: 60s
      max_worker_memory: 128

reload:
  enabled: true
  interval: 1s
  patterns: [".php", ".yaml", ".xml"]
  services:
    http:
      recursive: true
      dirs: [ "." ]
      ignore: ["var", "vendor", ".git", ".idea"]

logs:
  mode: development
  channels:
    http:
      level: debug
    server:
      level: info
      mode: raw
    metrics:
      level: debug

